<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <!--
    FASE 2 RADAR
    Este proyecto posee físicamente los modelos y servicios de interpretación.
    El Agent consume este ensamblado mediante ProjectReference.
  -->

</Project>
